package themes

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/gjermundgaraba/theme/colors"
)

const ansiContrastPolicy = "ANSI black and white slots are documented terminal extremes. Semantic syntax colors, UI text pairs, selections, search, diffs, buttons, and target progress/status pairs are validated."

type paletteReport struct {
	Source             string              `json:"source"`
	ANSIContrastPolicy string              `json:"ansiContrastPolicy"`
	Themes             []themeReviewReport `json:"themes"`
}

type themeReviewReport struct {
	Name           string                 `json:"name"`
	Type           string                 `json:"type"`
	Tokens         []colors.PaletteToken  `json:"tokens"`
	ContrastChecks []colors.ContrastCheck `json:"contrastChecks"`
	ANSINotes      []ansiNote             `json:"ansiNotes"`
}

type ansiNote struct {
	Slot  string `json:"slot"`
	Token string `json:"token"`
	Hex   string `json:"hex"`
	Note  string `json:"note"`
}

func renderPaletteReports(allThemes []ThemeData) error {
	report := paletteReport{
		Source:             "Generated by gg-theme from colors.Palette. Do not hand-edit build output.",
		ANSIContrastPolicy: ansiContrastPolicy,
		Themes:             make([]themeReviewReport, 0, len(allThemes)),
	}
	for _, td := range allThemes {
		report.Themes = append(report.Themes, themeReviewReport{
			Name:           td.Name,
			Type:           themeType(td.Name),
			Tokens:         colors.PaletteTokens(td.Palette),
			ContrastChecks: colors.ContrastChecks(td.Palette),
			ANSINotes:      ansiNotes(td),
		})
	}

	jsonData, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	jsonData = append(jsonData, '\n')
	if err := atomicWriteFile(filepath.Join("build", "palette.json"), jsonData, 0o644); err != nil {
		return err
	}
	fmt.Printf("  \033[32m✓\033[0m %s\n", filepath.Join("build", "palette.json"))

	md := renderPaletteMarkdown(report)
	if err := atomicWriteFile(filepath.Join("build", "palette.md"), md, 0o644); err != nil {
		return err
	}
	fmt.Printf("  \033[32m✓\033[0m %s\n", filepath.Join("build", "palette.md"))
	return nil
}

func themeType(name string) string {
	if strings.Contains(name, "light") {
		return "light"
	}
	return "dark"
}

func ansiNotes(td ThemeData) []ansiNote {
	if themeType(td.Name) == "dark" {
		return []ansiNote{{Slot: "ansiBlack", Token: "Black", Hex: td.Black, Note: "May be low contrast on BG by terminal convention."}}
	}
	return []ansiNote{
		{Slot: "ansiWhite", Token: "White", Hex: td.White, Note: "May be low contrast on BG by terminal convention."},
		{Slot: "ansiBrightWhite", Token: "BrightWhite", Hex: td.BrightWhite, Note: "May be low contrast on BG by terminal convention."},
	}
}

func renderPaletteMarkdown(report paletteReport) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated Palette Review")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, report.Source)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "**ANSI contrast policy:** %s\n", report.ANSIContrastPolicy)
	for _, theme := range report.Themes {
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "## %s (%s)\n", theme.Name, theme.Type)
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Tokens")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "| Token | Hex | OKLCH | Role |")
		fmt.Fprintln(&b, "|---|---:|---|---|")
		for _, token := range theme.Tokens {
			fmt.Fprintf(&b, "| `%s` | `%s` | `%s` | %s |\n", token.Name, token.Hex, token.OKLCH, token.Role)
		}
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "### Contrast checks")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "| Pair | Text | Background | Ratio | Minimum | Result |")
		fmt.Fprintln(&b, "|---|---:|---:|---:|---:|---|")
		for _, check := range theme.ContrastChecks {
			result := "pass"
			if !check.Pass {
				result = "fail"
			}
			fmt.Fprintf(&b, "| %s | `%s` | `%s` | %.2f | %.2f | %s |\n", check.Label, check.Text, check.BG, check.Ratio, check.Minimum, result)
		}
		if len(theme.ANSINotes) > 0 {
			fmt.Fprintln(&b)
			fmt.Fprintln(&b, "### ANSI exceptions")
			fmt.Fprintln(&b)
			for _, note := range theme.ANSINotes {
				fmt.Fprintf(&b, "- `%s` (`%s`, `%s`): %s\n", note.Slot, note.Token, note.Hex, note.Note)
			}
		}
	}
	return b.Bytes()
}
